# Site settings
title: Streamer Theme
email: bradykondek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Dynamic theme for streamer websites
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bradykondek.github.io/streamer/" # the base hostname & protocol for your site
#twitter_username:
github_username: bradykondek

# Build settings
markdown: kramdown
